# ----------------------------------------------
#        service.yml for FilePusher.py
# ----------------------------------------------
#       Please ensure UNIX EOL, UTF-8
# ----------------------------------------------

Database:
  # Choose one: cs01, cs02, vs02, vs03, vs04
  DBUser: cs01
  DBName: filepusher
  DBAddr: ""

Machine:
  FreeSpace: 15000000000

Folders:
  # This is the folder that will hold the temp folder until whole set is moved 
  # to a target.
  TempMoveFolder: "z:/filepusher_temp/"


Threads:
  # This is the max number of copy processes that the system will allow.
  ConcurrentCopies: 4

Products:
  # These are the watch folders and their settings.
  - Name: VidEv_FileSets
    ProductID: 0
    WatchPath: "z:/Upload/Movies/"
    WatchPattern: "*.smil"
    ValidateViaSmil: True
    SingleFiles: False
  - Name: VidEv_Singles
    ProductID: 1
    WatchPath: "z:/Upload/Single_Files/"
    WatchPattern: "*.mp4"
    ValidateViaSmil: False
    SingleFiles: True

Notify:
  - Name: Jim Holladay
    Email: 
    Slack: jim.holladay
    SMS: 
    Errors:
      - Email: True
        Slack: False
        SMS: False
    Admin:
      - Email: True
        Slack: False
        SMS: False
